weather:
  api:
    key: ${WEATHER_API_KEY:MOCK_KEY}
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /journal
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:MOCK_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:MOCK_SECRET}
  main:
    allow-circular-references: true
  redis:
    data:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/journaldb}
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL:mock@gmail.com}
    password: ${JAVA_EMAIL_PASSWORD:mock_pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.eng.journalApp.model
    properties:
      security:
        protocol: ${KAFKA_PROTOCOL:PLAINTEXT}
      sasl:
        mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      #  jaas:
      #    config: org.apache.kafka.common.security.plain.PlainLoginModule required username='X' password='X';
      session:
        timeout:
          ms: 45000